### ISSUE TITLE
Feature: Sitewide features for multipress

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#102]
This is not a comprehensive list, but the following features would be very nice for anyone running a multisite WP and using BA:

* Sitewide calendars -- Calendars which are visible on any of the sites. They can be booked from any of the sites, for example.
* Sitewide Booking Credits -- Users can use their booking credits to book anything on any subsite (for which booking is available)
* Master Calendar -- For admins to see the aggregate of all calendars on all of the subsites.

I realize that multisite is a bit "niche", but these features would be great.

Please ask any questions you may have.

**Comment by yoancutillas** [comment]
Thank you for your requests!
Unfortunately, these feature requests sound technically not realizable to me because each site has their own tables in the database, and each element (calendar, activities, events, forms....) have their own IDs that can be the same on each site. Booking Activities is designed to work with one single table per element, each having a unique ID.

**Comment by pikurasa** [comment]
I see.

I know some other plugins are able to do things at the multisite level.

Have you looked at Events Manager? One of the things it does really well is give the user multisite options.

A simple way to see what that means on the front end, is:
mapflc.com/events/ (site-wide events)
https://online.mapflc.com/events/ (events specific to subdomain online)
https://malden.mapflc.com/events/ (events specific to subdomain malden)

(Overall I like Events Manager, but they have not implemented new features for quite some time, unfortunately, and are missing some core features that BA has.)

**Comment by yoancutillas** [comment]
That's nice indeed! 
I didn't mean that it was not doable because of how Wordpress handles things, but because of how Booking Activities is designed. It would have been possible if this was taken into account from the begenning. Now, this would mean to pretty much rewrite everything and, even though, complexify a lot all of the current and future processes, that's why this feature doesn't sound feasible to me now.

**Comment by pikurasa** [comment]
bummer...

**Comment by pikurasa** [comment]
@yoancutillas is it possible, by any chance, to have just the booking credit feature be usable across a multisite WP?

I have some customers that have booking credits on one sub-site (dedicated to online classes) that are also scheduling activities on another sub-site (dedicated to in-person at a particular location).

If just this one feature were possible across a multipress WP, I think it would be game-changing for someone like myself.
