### ISSUE TITLE
Override the WC Pricing on BA pages (for Marketing Help)

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#121]
I have some events that are hundreds of USD per month.

On the WooCommerce Product Page, at the very top, you see the price. Because activities are not just a simple product price, but also a duration of time, I need some help otherwise I am misunderstood by some of my prospective customers. I would like features to help me better contextualize the price for my customers.

For example:
- $400 per month!
- $30 per day!
- $100 per week!

Or maybe even:
- From Just $30 per day!

Please advise. If there is an existing WC feature or plugin that I am somehow missing, please let me know. However, if no such thing exists (and maybe even if it does exist) I think this sort of future would be very helpful for BA users (like myself) who are using the plugin to sell activities for monetary compensation. Thanks in advance!

**Comment by yoancutillas** [comment]
With the [Prices and Credits](https://booking-activities.fr/en/downloads/prices-and-credits/) add-on, since 1.6.0, you can set up a custom text instead of the price displayed (see [this post](https://booking-activities.fr/en/blog/prices-and-credits-1-6-booking-passes-availability-period-display-total-price/#wc-custom-product-price)).
Go to Products > All products > your product > Product data > General tab > "Price to display" option.
