### ISSUE TITLE
No end date on notification email

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#133]
When reschedule an activity, it does not (also all shortcodes)  give any end date. Our activities last 8 weeks. So end dates are important. Is there a way to have that put in?

**Comment by yoancutillas** [comment]
If the dates are not displayed when you select an event on the calendar, or when a notification is sent, it may be due to the date formats. 

Can you make sure the date format are set as below in Booking Activities > Settings > Messages tab:
- Complete date and time format = l, F jS, Y H:i
- Short date and time format = F, jS - H:i
- Time format =  H:i

If it doesn't solve the issue, can you send me screenshots showing the issue, I am not sure to understand.
