### ISSUE TITLE
Availability particle not show on quantity of 1? 

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#149]
I am a bit puzzled. 
I am trying to hide availability(quantity particle text)  if greater than 0.
Availability setting is on 1%. But it already removes the particle 'beschikbaar'on quantity of 1 instead of 0. and the quantity becomes hidden.

I removed all custom code and css.

What I eventually would like to achieve is the same, the way WC does:

QUANTITY     PARTICLETEXT
0                      FULL
1-3.                 only x available! (set threshold)
4-infinite        x available
<img width="1139" alt="Screenshot 2022-05-06 at 08 06 16" src="https://user-images.githubusercontent.com/6242489/167076266-fceb0409-abd0-44ef-b060-8198111142d7.png">
<img width="437" alt="Screenshot 2022-05-06 at 08 08 13" src="https://user-images.githubusercontent.com/6242489/167076394-9c2b45fe-e731-4e46-a67c-fa8f857da79f.png">

**Comment by yoancutillas** [comment]
If you set "Hide availability if greater than" to "1%", indeed, the availability will most likely always be hidden (unless your events availability is very high).
Set it to to a higher percent to keep the availability displayed a bit more. E.g.: if your events availability is "20", then set it to "30%" to display the availability between 0 and 6.

You cannot achieve the same as WC without custom code. Booking Activities only allows to hide the event availability if greater to a certain percent. #140 describes how to add "only" before and "!" after the availability text with CSS only, but it would be regardless of the remaining number. If you need to take the avilability number into account, you would need to make custom javascript code.

Note that in the next release, the "Hide availability if greater than" option will hide (in CSS) the whole availability text instead of hiding only the number.

**Comment by yoancutillas** [comment]
Oh, sorry, regarding the "Beschikbaar" that is not displayed, you may be missing a translation (the "avail." text must be translated in both singular and plural), see the instructions below "Translate Booking Activities into my language" here: https://booking-activities.fr/en/documentation/faq/

**Comment by rayedgar** [comment]
I understand the logic. But I do not see the availability particle when quantity is exactly equal to 1 (out of 9). When above 1. It does show the particle. Availability is set to 100%

**Comment by rayedgar** [comment]
Ah yes! the plural setting, that was it! now the logic is back again.  Many thanks and look forward to the next version!

**Comment by yoancutillas** [comment]
Sorry this feature is not planned, the next version will simply hide (in CSS) the whole availability text instead of hiding only the number.

I have noted your feature request, thank you.

**Comment by rayedgar** [comment]
Thank you!

**Comment by yoancutillas** [comment]
I cannot provide support for custom code, but here is an example in the hope to help:
- Go to Booking Activities > Booking forms > your form > Calendar settings > Display tab > set "Hide availability if greater than" to "60%", or any percent you like for the "Lots of places available" case
- Go to Appearence > Customize > Additional CSS and add something like that:
```
/* Lots of places available */
.bookacti-availability-container.bookacti-hide-availability { display: block; }
.bookacti-availability-container.bookacti-hide-availability .bookacti-available-places-number::before { content: "Lots of "; }
/* Few places left */
.bookacti-availability-container:not(.bookacti-hide-availability) .bookacti-available-places-number::before { content: "Only "; }
.bookacti-availability-container:not(.bookacti-hide-availability) .bookacti-available-places-avail-particle::after { content: "!"; }
/* Full */
.bookacti-availability-container .bookacti-full > span { display: none; }
.bookacti-availability-container .bookacti-full::before { content: "Full"; }
```

**Comment by rayedgar** [comment]
thank you, that works!
