### ISSUE TITLE
Show scrollbar in listview

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#151]
I use the calendar list view. The list is very long but because the scrollbars are hidden users do not scroll down.
I tried using CSS:
overflow-y:scroll on body and on: .bookacti-calendar.fc.fc-unthemed.fc-ltr

But it does not seem to work. Would there be a solution for this?

**Comment by yoancutillas** [comment]
The scrollbar is displayed by default ([demo](https://demo.booking-activities.fr/en/shop/calendar-display-types/)), 
Go to Booking Activities > Booking forms > your form > Calendar settings > Calendar tab > Show advanced option >
- Set the desired Height in the "Height" or "Content height" option.
- Empty the other "Height" or "Content height" option
- Empty the "Aspect ratio" option

Otherwise, it is probably hidden by a third party plugin / theme CSS.
You can follow the instructions below "Booking Activities doesn’t work as it should" here: https://booking-activities.fr/en/documentation/faq/ in order to indentify it.

In any case you can probably fix it with custom CSS in Appearence > Customize > Additional CSS.

**Comment by rayedgar** [comment]
The scrollbar is indeed viewable only when scrolling. It hides when not scrolling.

I figured it out in css and i share this for other users:

.fc-scroller::-webkit-scrollbar {
	-webkit-appearance: none;
	width: 10px;
  }
 .fc-scroller::-webkit-scrollbar-thumb {
	border-radius: 4px;
	background-color: rgba(179, 96, 67, 1);
	box-shadow: 0 0 1px rgba(255, 255, 255, .5);
  }
  
 This shows the scrollbar at all times. So it's more intuitive for the user.

Thanks for your reply.

**Comment by yoancutillas** [comment]
Thanks for sharing your solution!
