### ISSUE TITLE
(Message notifications) Add an "opt out of these messages" etc. to avoid flagged as spam

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#152]
Recently, Gmail has been refusing to deliver all notifications.

I don't know what the solution would be, but I do think that adding the same things one would to a newsletter, such as "opt out" and "change preferences" and a section to add company address etc. may help these things land in people's mailbox.

Also, I think it would be a good feature, anyway, as some customers want to opt-out of notifications anyway.

(Feel free to close/merge this issue if already mentioned elsewhere. I did a quick look and did not see it.)

**Comment by pikurasa** [comment]
To be clear, I am sending email via Gandi's email services. It is customers who are using Google services who are not receiving their emails.

I skimmed the link you sent, and it seems to be about how to send email via Google, which is not what I am doing.

**Comment by yoancutillas** [comment]
Ok, so the email are sent, but not received (for gmail users only)?

The sender's address in Booking Activities > Settings > Notifications tab must be that of your SMTP server.

In most cases, the SMTP server of the host is used, so you must create an e-mail address at the host and enter it here.

In your case you are using Gandi, I don't know about this tool, but if it changes the SMTP server then you may need to change the sender address accordingly.

**Comment by pikurasa** [comment]
> Ok, so the email are sent, but not received (for gmail users only)?

Yes, they are sent, but not received. Gmail sends a message as a reply to tell me that they have been rejected.

```
I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<customeremail@gmail.com>: host gmail-smtp-in.l.google.com[IP-address] said:
    550-5.7.1 [IP-address] Our system has detected that this
    message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam
    sent to Gmail, 550-5.7.1 this message has been blocked. Please visit
    550-5.7.1  https://support.google.com/mail/?p=UnsolicitedMessageError 550
    5.7.1  for more information.
    h5-20020a05600016c500b00216093052a2si3830427wrf.239 - gsmtp (in reply to
    end of DATA command)
```

**Comment by yoancutillas** [comment]
Make sure that the sender's address in Booking Activities > Settings > Notifications tab > **From email** is known by your SMTP server. I think that's the problem+

Try to contact your SMTP server support anyway to ask about that issue. Have them confirm what sender email address you should use to make sure your are using the correct one according to your configuration.

_(you can technically usurpate the email address of anyone, but the email clients such as gmail are no fools, they verify if the sender email address matches the sender server (the SMTP server), some SMTP servers even prevents the email from being sent in the first place in such cases, that's why you need to make sure that the sender email address matches the SMTP server used to send the email)._

Otherwise, I found that official docs:
https://support.google.com/mail/thread/142737112?hl=en
https://support.google.com/mail/answer/81126?hl=en

**Comment by yoancutillas** [comment]
Closed because being flagged as spam is a separate individual issue, transactional emails are not to be opt out, and an option to opt out reminder notifications has been added ([docs](https://booking-activities.fr/en/blog/notification-pack-1-3-support-more-sms-providers/#user-notification-settings)).
