### ISSUE TITLE
Phone number required

### ISSUE THREAD

**Issue by dominiozero** [bookingactivities/booking-activities#159]
**Describe the bug**
Despite having configured the phone field as required, in the frontend the user can create a reservation without indicating the phone number.

**To Reproduce**
- Just installed:
-- Booking Activities
-- Booking Activities - Display Pack
-- Booking Activities - Licenses & Updates
-- Booking Activities - Prices & Credits

- Create a new Booking form.
- In User Data section, click the gear icon, click on Show advanced options.
- Set the Phone number field as required.

**Screenshots**

![Captura de pantalla 2022-08-29 111530](https://user-images.githubusercontent.com/62662715/187167739-ae800578-ce16-4dea-a9ba-9487c5ab2779.jpg)

![Captura de pantalla 2022-08-29 111711](https://user-images.githubusercontent.com/62662715/187168752-1a6900ee-ff21-4975-86f0-c59102b6b526.jpg)

**Expected behavior**
It should set the field as required.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Booking Activities, its add-ons, and WooCommerce are activated.
- [ ] This bug happens with the default WordPress theme Twenty Seventeen.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Wordpress: 6.0.1
PHP: 7.4.30
MySQL: 5.5.5
Booking Activities: 1.14.3
Display Pack: 1.4.24
Prices and Credits: 1.7.7

**Comment by yoancutillas** [comment]
Thank you, on your screenshot, I can see that the booking were made with WooCommerce.
With WooCommerce, the User Data field is not used. There used to be a feedback to inform about it but it seems to have disappeared since 1.14, I'll fix it in the next release.
![Capture](https://user-images.githubusercontent.com/9415030/187201735-39957a81-7769-44cc-9caa-7c4094656da6.PNG)


You need to get the phone number with WooCommerce on the checkout page. 
By default, the phone number is required on the checkout page, so if it is not required on your site, it may be due to a third party plugin / theme.
![checkout](https://user-images.githubusercontent.com/9415030/187202735-8eec9d0b-dc3e-4e03-b887-4b60115e824b.png)

([Otherwise, maybe this custom code can help](https://www.tychesoftwares.com/how-to-make-fields-mandatory-or-optional-on-the-woocommerce-checkout-page/)).

**Comment by dominiozero** [comment]
Right! It was a third party plugin we used to hide some fields, as we thought that entering the phone number in the reservation field it was already saved, regardless of whether the reservation was made with WooCommerce or not.
