### ISSUE TITLE
Cart Expiration Count Down is not visible on the page

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#188]
Hi,
I am facing a strange issue. When booking an event, I get redirected to the cart page but the Expiration count down isn't visible although by check the source code I see its visible (screenshot attached). I have the following settings in booking activities WooCommerce tab:
Cart settings> Activate cart expiration: Selected
Timeout (minutes): 30

Can you please guide me on how this can be fixed? Thanks 

![bookingact_expiration](https://user-images.githubusercontent.com/30695308/224886259-96c664db-dc98-48a6-8c04-90fef49cab0d.png)

**Comment by yoancutillas** [comment]
Hello,
This issue may be due to a conflict with a third party plugin / theme,
Can you follow the instructions below "Booking Activities doesn’t work as it should" here: https://booking-activities.fr/en/documentation/faq/ ?

**Comment by yabdali** [comment]
> Hello, This issue may be due to a conflict with a third party plugin / theme, Can you follow the instructions below "Booking Activities doesn’t work as it should" here: https://booking-activities.fr/en/documentation/faq/ ?

Using the default seem doesn't fix the problem! Any further suggestion? 
![bookingexpire](https://user-images.githubusercontent.com/30695308/225175874-a619cc07-3316-4471-aeac-6cf374a72c5a.png)

**Comment by yoancutillas** [comment]
Thank you,

The issue is that the js/woocommerce-frontend.min.js file is not loaded on your site.
Actually, almost none of the Booking Activities' javascript files are loaded on your cart page, which is abnormal.

This may be due to a caching / optimizing system, maybe on the server side. Can you check on your side, ask your webhost, and deactivate them if any are active?

If this doesn't fix the issue, I will need an administrator access to your website or to a development website where I can reproduce the issue (all plugins must be deactivated except Booking Activities and WooCommerce, and the Twenty TwentyThree theme active). You can send it to contact@booking-activities.fr.
