### ISSUE TITLE
Date planning with caracters : â€“

### ISSUE THREAD

**Issue by titiph56** [bookingactivities/booking-activities#189]
Hi,

In the planning, the date for a week displays characters : â€“

How can i fix this character problem ?

Thank you for your help !

The page I need help with: https://beatricethibault.com/agenda/

**Comment by yoancutillas** [comment]
The issue doesn't reproduce on my side with Firefox 110 (tested on Windows 11, and Windows 10).
This issue is probably related to your browser configuration (maybe an extension, or a setting) (there are few topics about it with various solutions to try: [quick search](https://www.google.com/search?q=firefox+displays+%C3%A2%E2%82%AC%E2%80%9C)).

**Comment by titiph56** [comment]
I updated firefox and it worked, thanks
