### ISSUE TITLE
one of calendars not visible when logged in as non administrator

### ISSUE THREAD

**Issue by rayedgar** [bookingactivities/booking-activities#195]
When logged in as editor (so the option of selecting calendars are hidden?) . One of the two calendars in the calendar editor are not visible.
But when deselect the 'booked' option in filter. and then select 'booked' option again it is shown again.

an other way is when i use the hide/show calendar button, it shows the hidden calendar again.
This bug was there a while ago. and seems to have come back.

The other issue is that 

https://github.com/bookingactivities/booking-activities/assets/6242489/589e9afc-e9f1-4bd7-a7d4-5ece52603a5f

even when the calendar is shown and clicked on, there is nothing shown in the records under the calendar
I can reproduce this.

**Comment by yoancutillas** [comment]
Hello Ray, thanks for reporting, it looks like there is an issue in the permission system and settings.

Can you follow [this documention](https://booking-activities.fr/en/docs/user-documentation/advanced-use-of-booking-activities/give-access-rights-to-calendars-and-bookings-to-your-collaborators/) to properly set up the permission?

I think there are 
- an issue in your configuration to grant access to the bookings to the Editor (that can be fixed thanks to the documentation above) 
- and a bug in Booking Activities, because your video shows an abnormal behaviour.

**Comment by rayedgar** [comment]
The permissions where all assigned. Will wait for the bug fix. Thanks

**Comment by yoancutillas** [comment]
The bug that I have identified and that I can reproduce is that you should _not_ see the additional bookings when you reload the calendar (it should be the same as when you load the page the first time).

If you do want to see them and the booking list, you need to add the desired user as manager in both calendar settings and set the following permissions with User Role Editor: bookacti_manage_booking_activities, bookacti_manage_bookings, bookacti_edit_bookings, bookacti_delete_bookings.

Can you send me these three screenshots please:

Can you go to Booking Activities > Calendar editor > 
- select the first calendar > click the "settings" icon next to the calendar selectbox > Permissions tab > I need to see the value of "Who can manage this calendar?"
- select the second calendar > click the "settings" icon next to the calendar selectbox > Permissions tab > I need to see the value of "Who can manage this calendar?"

Can you install and activate [User Role Editor](https://wordpress.org/plugins/user-role-editor/), then go to Users > All users
- mouseover the desired user > Capabilities > I need to see all the boxes starting with "bookacti_" and the left column (Primary Role / Other Roles)
