### ISSUE TITLE
Caching Considerations

### ISSUE THREAD

**Issue by yabdali** [bookingactivities/booking-activities#209]
This is just a general inquiry. We are intending to use [WP Super Cache](https://wordpress.org/plugins/wp-super-cache/) and wanted to know if there are any specific recommendations to avoid having a conflict since the plugin has different options related to preloading and serving semi static content apart from excluding /wp-admin/admin-ajax.php? Appreciate your advice and suggestions, thanks.

**Comment by yoancutillas** [comment]
No, I have tested WP Super Cache with Booking Activities in 2020 with the default settings and it worked properly. The demo website uses Speed Optimizer (by Siteground) with Dynamic Caching and Memcached without issue. It used to use W3 Total Cache and it worked perfectly as well.

Booking Activities uses WP cache API where it needs to and enqueues minified javascript files in the correct order, in the footer, except for js/global-var.min.js that must be loaded in the header. So if WP Super Cache sticks to it it should be fine.

If you are using the Notification Pack add-on and Push notifications, exclude this file from any optimization process:
/wp-content/plugins/ba-notification-pack/js/firebase-messaging-sw.min.js/

I personally recommend disabling JS minification and concatenation as it is a major source of troubles for a minor gain since most plugins already minify their JS and CSS files.
