### ISSUE TITLE
Multiple Times of one Activity

### ISSUE THREAD

**Issue by shahidsaeed** [bookingactivities/booking-activities#32]
Is there any possibility to have multiple time duration of each activity. For example an activity comprises on 2 hours each day for multiple days?

**Comment by yoancutillas** [comment]
Booking Activities' concept is to drag'n drop a events onto a calendar, and then, the customer clicks on the event to book it. Your customer cannot choose the event duration.

If your event can last, say, between 30mn and 2h. You can:
- set multiple events of 30mn one after the other, so the customer can book 30mn, 2x 30mn, 3x 30mn or 4x 30mn.
- set one event of 2h and then add a field to ask for the desired duration (with the [Advanced Forms](https://booking-activities.fr/en/downloads/advanced-forms/) add-on)
- set one event on 30mn, one event of 1h, one event of 1h30, and one event of 2h side by side. Then, in order to disable one event when the other is booked, follow the steps in [this answer, option 3](https://github.com/bookingactivities/booking-activities/issues/29#issuecomment-508474476)
