### ISSUE TITLE
Booking Form Redirect from Calendar (multisite)

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#34]
(I have a multisite WP, using subdomains for the child sites -- I assume that the issue only happens on Multisite WP, but have not tested elsewhere)

The link I am given to create a booking form after creation of a calendar is:

https://subdomain.mysite.com/wp-admin/admin.php?calendar_field%5Bactivities%5D%5B%5D=29&calendar_field%5Bactivities%5D%5B%5D=28&page=bookacti_forms&action=new&calendar_field%5Bcalendars%5D%5B%5D=8&calendar_field%5Bgroup_categories%5D%5B%5D=all

which takes me to:
https://mysite.com/wp-admin/network/admin.php?page=bookacti_forms&action=edit&form_id=xyz

which does nothing

(I have been using Booking Activities for a few months with a paid license. I sent an email with a short report a few months ago, but probably it was not seen. That is okay, as I found a workaround, but please fix.)

Workaround: In the meantime, I have been correcting the problem myself by rewriting the URL to:
https://subdomain.mysite.com/wp-admin/admin.php?page=bookacti_forms&action=edit&form_id=xyz

(adding my subdomain for the multisite and deleting `network/`. It was an educated guess, and it worked)

**Comment by yoancutillas** [comment]
Hello Devin,

Yes, this is a bug due to multisite,
Booking Activities doesn't support it officially (not being tested with).

But I think I just need to change the [get_admin_url](https://developer.wordpress.org/reference/functions/get_admin_url/) function to [admin_url](https://developer.wordpress.org/reference/functions/admin_url/) to fix it, will do for the next release, thanks for reporting!

I haven't received any emails I haven't answered, sorry for that, if I don't answer within 48h, there is most likely a technical problem.

Regards,
Yoan

**Comment by pikurasa** [comment]
> Yes, this is a bug due to multisite,
> Booking Activities doesn't support it officially (not being tested with).

For not being tested, it actually works pretty well, so I kind of assumed it was supported.

**Comment by yoancutillas** [comment]
Thank you for your feedback!
Well, I do fix the bugs related to multisite when they are reported, it is just a lack of guarantee.

**Comment by pikurasa** [comment]
Thanks. I will test.

**Comment by pikurasa** [comment]
It works!
