### ISSUE TITLE
English Spelling errors

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#36]
I have seen a few spelling errors in documentation and in the front end (of admin).

In settings
> of the small white icon that will be displayed in the status bar (on mobile only). Recommanded size: 128x128px.

Recommended

Actually, I would be happy to make the edits. Which file has the English translations?

**Comment by yoancutillas** [comment]
Thank you for reporting, I will fix it in the next release.

Unfortunately, the english texts are the originals, not translation. They are in the source code and cannot be changed.

Actually, you can make your own translation using another english locale (en_GB instead of en_US for example). 
For the main plugin, the tutorial is [here under "Translate Booking Activities into my language"](https://booking-activities.fr/en/documentation/faq/)
For the add-ons, it is the same, just skip step #1, and name the .po and .mo accordingly. 
E.g.: For the Notification Pack translation in the en_GB locale:
- `wp-content\languages\plugins\ba-notification-pack-en_GB.po`
- `wp-content\languages\plugins\ba-notification-pack-en_GB.mo`

**Comment by pikurasa** [comment]
> Actually, you can make your own translation using another english locale (en_GB instead of en_US for example).

I don't think this method for fixing spelling errors is really worth it. Also, as an American English speaker, I may sometimes (unintentionally) introduce errors to a GB English translation based on my assumptions of the English language. The two are very closely related but not exactly the same.

At any rate, I don't think it is a really big issue, but one to keep on the radar. I will try and report as I see them.
