### ISSUE TITLE
Permissions set, but managers are not available for selection (Multisite)

### ISSUE THREAD

**Issue by pikurasa** [bookingactivities/booking-activities#37]
I have three users that I have granted shop_manager and operator permissions to, however they do not show up in the dropdown.

I just read https://booking-activities.fr/en/docs/user-documentation/advanced-use-of-booking-activities/give-access-rights-to-calendars-and-bookings-to-your-collaborators/ and it seems that the necessary permissions are selected for shop_manager (which two of the users are assigned).

Perhaps this is another multisite issue? (I think, fwiw, we are getting to the bottom of the list for multisite incompatibilities)

Other notes:
When I first installed the plugin, the dropdown worked and I was able to select privileged users. Since about 2 months ago, I have not been able to do so.

What I could try:
I have some permissions from plugins that I have since deleted (but the SQL data seems to remain) that I could try to remove.

What you may try:
Perhaps the issue is that some of the users created their accounts from the subaccount and thus they have a prefix (or something like that) on their data, which is being overlooked by Booking Activities.

**Comment by yoancutillas** [comment]
Thank you for your testing and reports with multisite feature!

The code for listing the users hasn't changed since 1.7.4 (June 2019, 6th), espacially for multisite support. Does it match the period when it stopped working?

Here is the simplified code if it helps:
`
$in_roles = apply_filters( 'bookacti_managers_roles', array() );
$not_in_roles = apply_filters( 'bookacti_managers_roles_exceptions', is_multisite() ? array() : array( 'administrator' ) );
$user_query = new WP_User_Query( array( 'role__in' => $in_roles, 'role__not_in' => $not_in_roles ) );
$users = $user_query->get_results();
foreach( $users as $user ) {
	if( $user->has_cap( 'bookacti_edit_templates' ) || $user->has_cap( 'bookacti_read_templates' ) ) {
		// Display the user in the selectbox
	}
}
`

If I am not mistaken, the users and roles are registered at both the network level and the blog level?
In that case, can you try the following:
1.
With User Role Editor, add the 'bookacti_edit_templates' capability to the desired **role** in the desired **blog** admin panel. Then try to add a user having this role as manager.
2.
With User Role Editor, add the 'bookacti_edit_templates' capability to the desired **user** in the desired **blog** admin panel. Then try to add this user as manager.
3.
With User Role Editor, add the 'bookacti_edit_templates' capability to the desired **role** in the **network** admin panel. Then try to add a user having this role as manager.
4.
With User Role Editor, add the 'bookacti_edit_templates' capability to the desired **user** in the **network** admin panel. Then try to add this user as manager.

Can you also try to add this code in your child theme functions.php, just to make sure that the roles are not restricted:
`
add_filter( 'bookacti_managers_roles', function($roles){ return array(); }, 1000, 1 );
add_filter( 'bookacti_managers_roles_exceptions', function($roles){ return array(); }, 1000, 1 );
`

**Comment by yoancutillas** [comment]
Just noticed that WP_User_Query has an implicit parameter:
`'blog_id' => get_current_blog_id()`

It means that the user must be registered at the blog level, not only at the network level, is it the case?

**Comment by pikurasa** [comment]
> It means that the user must be registered at the blog level, not only at the network level, is it the case?

I may not know how to test your question, but I can tell you the following:
* My user is at network level
* When I add myself as an "operator" it breaks many of the plugins on my dashboard (i.e. I can no longer see them)
* When I remove myself as an "operator", it reverses the problem stated above

Would you like me to test your theory by creating a user at the blog level and then setting their role as a "manager"/"operator", then seeing if I am able to add them (as an admin)? (I think this presumes that the network admin *is* able to add someone.) At any rate, happy to test anything, but please give me a test you think will help.

**Comment by yoancutillas** [comment]
Thank you for these additionnal information,

The "Operator" role intentionnally removes the UI in order to prevent him to go where he is not allowed to. It works with Booking Activities and WooCommerce, for the other plugins, it requires additionnal coding to hide / show what necessary. This is the [intended UI for the Operator](https://booking-activities.fr/wp-content/uploads/operator-admin-interface.png). 

If you just want a user / a role to be able to make bookings on behalf of customers, grant him the "order_for_customers" capability with [User Role Editor](https://wordpress.org/plugins/user-role-editor/).

Now, WP_User_Query only shows the users at the blog level. So if your user is at the network level, it is normal that he isn't listed. Can you try to replace this line:
`$user_query = new WP_User_Query( array( 'role__in' => $in_roles, 'role__not_in' => $not_in_roles ) );`
with
`$user_query = new WP_User_Query( array( 'blog_id' => is_multisite() ? 0 : get_current_blog_id(), 'role__in' => $in_roles, 'role__not_in' => $not_in_roles ) );`
in these files:
- wp-content\plugins\booking-activities\view\view-templates-dialogs.php line 21
- wp-content\plugins\booking-activities\functions\functions-forms.php line 1521

and tell me if the network users (having the appropiated capability) are now listed?

**Comment by pikurasa** [comment]
> and tell me if the network users (having the appropriate capability) are now listed?

I can now see network users (i.e. myself as admin user), but I do not see any of the other "shop managers" or "operators". I checked just now, and those users seem to be at the blog level.

Hope that helps!

**Comment by pikurasa** [comment]
Also, on "booking forms" page, it seems that I can add myself to the list but cannot remove myself (my user).

**Comment by yoancutillas** [comment]
Thank you for your feedbacks,
Sorry but it looks like I won't be able to fix it before I do the necessary to support the multisite feature as a whole (meaning setting the test environnement and making all the required tests and fixes). 

Unfortunatly I need to queue it in the to do list and add your vote to increase the priority for now. I hope to be able to offer the multisite support in the next major version 1.8.

**Comment by pikurasa** [comment]
> Sorry but it looks like I won't be able to fix it before I do the necessary to support the multisite feature as a whole (meaning setting the test environnement and making all the required tests and fixes).

I think that is wise as I imagine there are some corner cases that would need to be tested.

Thank you!

**Comment by yoancutillas** [comment]
After further testing, it appears that the WP_User_Query parameters were correct.
The problem was that Shop Managers were supposed to be able to manage any booking forms without needing to be added in the managers selectbox, just like administrators. So they were not displayed in the selectbox indeed, but the permissions checks were still performed, hence the bug.

So in the next update, I will revert the changes made to WP_User_Query parameters and bypass the manager checks for Shop Managers.

About Operators, you need to grant them these capabilities at the blog level: `bookacti_edit_forms` and `bookacti_manage_forms`. Then, you will be able to see them in the form managers selectbox and set them as manager of this form.

You cannot remove yourself from the manager selectbox indeed, the system will automatically add you if you are the one who are updating the settings anyway, except if your role bypass the manager checks. To fix it, log in as someone else who can remove you from the list.

**Comment by pikurasa** [comment]
I cannot really get this to work. I am not sure what I am doing wrong.

Is it required that I have Points of Sale plugin to use this feature?

**Comment by yoancutillas** [comment]
No it is not required,

I have made a video showing a working configuration:
[https://booking-activities.fr/wp-content/uploads/support/multisite-users-roles-and-capabilities.mp4](https://booking-activities.fr/wp-content/uploads/support/multisite-users-roles-and-capabilities.mp4)

Administrators and Shop Managers don't need to be manually added as managers, that's why they are not in the managers selectboxes.
You need to make sure **on every site** with User Role Editor, that the Administrator, Operator and Shop Manager roles have the proper capabilities.

**Comment by pikurasa** [comment]
I still have not been able to get this feature to work. In your video (many thanks for the video), you have the plugin network active. Is this necessary?

I have a user with both shop manager and operator for their roles, but I am not seeing them show up here:

![Screenshot at 2020-08-31 15:23:09](https://user-images.githubusercontent.com/13454579/91769720-e6aa2000-ebad-11ea-9810-66eaeb587030.png)

**Comment by yoancutillas** [comment]
No, you don't need to activate Booking Activities at the network level, you can activate it at the site level.
Shop Managers are an exception, like Administrators, they can manage everything. That's why they don't appear in the list.

**Comment by pikurasa** [comment]
Ok, now I got it!!!

Two suggestions:

* For the tooltip, say "All Administrators and Shop Managers already have this privilege."
* I recommend that you call operators BA_operators or something like that.

Another suggestion is it would be nice to have "operator" as an option for possible recipients of notification emails. That way, an event organizer could receive a reminder for upcoming events.

**Comment by yoancutillas** [comment]
Thank you, will do.

The "Operator" recipient is actually the same as "Administrator":
With the [Notification Pack](https://booking-activities.fr/en/downloads/notification-pack/) add-on, you can set per-activity recipients and send administrators' notifications to those recipients according to the booked event ([docs](https://booking-activities.fr/en/docs/user-documentation/get-started-with-notification-pack-add-on/set-specific-recipients-for-each-activity/)).

**Comment by pikurasa** [comment]
> you can set per-activity recipients and send administrators' notifications to those recipients according to the booked event (docs).

I just figured it out. Thanks.

(I made the incorrect assumption that "activity recipients" were only customers who were registered for the activity.)
