### ISSUE TITLE
Expire function in card (basket)

### ISSUE THREAD

**Issue by unomobil** [bookingactivities/booking-activities#4]
When activating the expire card funktion , im not able to write the adresse when trying to pay the ticket, if im luck im able to write my name, and then the other fields is unedible .

**Comment by bookingactivities** [comment]
Hello,

I guess you are using Booking Activities with WooCommerce and the fields your are talking about are the one on the checkout page, right?

If so, this may be due to a plugin or theme incompatibility. Can you please follow the instructions on this page:
https://booking-activities.fr/en/documentation/faq/
under the "Booking Activities doesn’t work as it should" question, and give me the results?

Thank you,
Regards,

**Comment by unomobil** [comment]
Yes Im using WP. 

I have looks in the FAQ , But it dident solv it, 

Sendt fra min iPhone

**Comment by bookingactivities** [comment]
Actually these instructions are not meant to solve the problem but to know where it comes from.
We know for sure that Booking Activities is working fine with only WooCommerce and Twenty Seventeen theme activated (with WP 3.6+, PHP 5.3+, WC 2.6+).

If you encounter an unexpected behavior, such as what you described, it is most likely because of a third party plugin or theme incompatibility.

That is why I suggest you to temporarily turn off all your plugins exept Booking Activities and WooCommerce, and activate Tweenty Seventeen theme. Then, test if it works between each activation and let me know what is the faulty plugin / theme.

Regards,

**Comment by bookingactivities** [comment]
Hello, 

Did you solve your problem or do you need more help?

Regards,
