### ISSUE TITLE
Activities fully booked does not display their tooltip

### ISSUE THREAD

**Issue by opcoach** [bookingactivities/booking-activities#58]
If their are seat lefts, activity can be selected and displays its tooltip. 
If it is fully booked, activities has no tooltip. 

Basically, even if an activity has no more seats left, it would be better to let the tooltip displayed... 

![NoTooltipOnBookedActivity](https://user-images.githubusercontent.com/1716878/74066655-cfc89400-49f7-11ea-97c7-8a0f68af4189.png)

**Comment by yoancutillas** [comment]
Thank you for your feedback,
I have had other requests for that, I will change this in the next update (1.7.18).

**Comment by opcoach** [comment]
Sorry Yoan,  but with 1.7.18 it does not work. 

See it on this page : https://www.interindep.com/formations/

Go over the pink event of the 11 of February (which is disabled probably because fully booked) and the tooltip is not displayed while on others it is..

**Comment by opcoach** [comment]
Or may be is it because the event is in the past ? If so, is there an option to allow tooltip anyway for events in the past ?

**Comment by yoancutillas** [comment]
No problem, since it is actually a CSS problem I should have tested the fix on several theme.
The problem is related to the z-index set to -1, I will remove that instruction in the next release.
You can try to add this code in Appearence > Customize > Additional CSS as a temporary fix:
`.bookacti-event-unavailable { z-index: 1!important; }`

**Comment by opcoach** [comment]
Fine it works with the css change... Thank you
