### ISSUE TITLE
Calendars not loading after update 1.8.2

### ISSUE THREAD

**Issue by ccusr33** [bookingactivities/booking-activities#71]
I just updated Booking Activities to v. 1.8.2 and now none of our calendars are loading for any users, not in the admin panel or in the product front-end (we are using WooCommerce). It just keeps saying "loading" with the spinning icon.

**Comment by ccusr33** [comment]
Screenshot of error in console
![bookingact_error_console](https://user-images.githubusercontent.com/65374183/81995223-b5660e00-9617-11ea-893d-e29fc0fbe436.JPG)

**Comment by yoancutillas** [comment]
Hello,

If you have Booking Actvities add-ons, you need to update them as 1.8 is not compatible with old add-ons versions.

To make sure, can you try to deativate **all** your plugins (including WooCommerce, and Booking Activities add-ons) except Booking Activities, and activate [Twenty Seventeen](https://wordpress.org/themes/twentyseventeen/) instead of your theme, and try again? (hard refresh the page with CTRL+F5 and empty your cache if you are using a cache plugin).
