### ISSUE TITLE
Cart items disappear after user login

### ISSUE THREAD

**Issue by blackhatwarrior** [bookingactivities/booking-activities#92]
Steps to reproduce the issue:
1. Add a booking product into cart as guest
2. Go to checkout page and login to your account

Items in your cart will disappear with error "Sorry, your session has expired". Also, if it's the last time slot available for booking, you can't book it again before 30 minutes timeout.

**Comment by yoancutillas** [comment]
Hello, I don't reproduce the issue on the [demo website](https://demo.booking-activities.fr/en/shop/calendar/), 

Can you follow the instructions below "Booking Activities doesn’t work as it should" here: https://booking-activities.fr/en/documentation/faq/ to check if this issue is due to a conflict with another plugin / theme?

**Comment by blackhatwarrior** [comment]
Hello, 

Can you please check again with Guest checkout disabled in Woocommerce?

![image](https://user-images.githubusercontent.com/40344151/106899139-045e5100-671b-11eb-8f82-66dedc98703d.png)

**Comment by yoancutillas** [comment]
Done, I don't reproduce the issue either.

Can you confirm that you can reproduce the issue with all your plugins
deactivated except Booking Activities and WooCommerce and with the Twenty
Seventeen <https://wordpress.org/themes/twentyseventeen/> theme active?

Regards,
Yoan Cutillas

**Comment by blackhatwarrior** [comment]
Hello, thank you for prompt reply. The issue was caused by WP Rocket: Caching Plugin. I've disabled it for now and will contact the developer to get it resolved.
