### ISSUE TITLE
New Feature: allow selected users to book all available places in activity

### ISSUE THREAD

**Issue by krzysztofmatula** [bookingactivities/booking-activities#97]
I normally have activities with several places available (group classes).
All are configured such way, that single user can book single activity only once (set in activity definition in calendar editor).

I'd like an option for administrators to simply book "all remaining places" - an. easy way for cancelling the event and blocking further people to sign up.

I can have a separate form for administrators allowing to pick the number of places to book, but still, the limit set in calendar won't allow to block more than just one place.

Maybe what I need is already available, but I can't determine how it could be achieved.
I'd appreciate any suggestions.

**Comment by yoancutillas** [comment]
1.
In order to remove the remaining places, you can decrease the event availability:
Go to Booking Activities > Calendar editor > go to the event settings (mouseover it, click the settings icon) > Decrease the "Availability" option.
If the event is repeated, you need to unbind it first to change the availability of this occurence only. In the event settings, click "Unbind" >  Unbind the selected occurrence.

2.
In order to cancel the event:
Go to Booking Activities > Calendar editor > go to the event settings (mouseover it, click the settings icon) > Click the "Delete" button ( > Optionally, turn ON the "Cancel the bookings" option if you want to cancel the bookings, and turn ON the "Send notifications" to notify the customers that their bookings were cancelled.)
If the event is repeated, you need to unbind it first to cancel this occurence only. In the event settings, click "Unbind" >  Unbind the selected occurrence.

**Comment by krzysztofmatula** [comment]
My all events are repeated.

What I normally do is to go to the calendar editor, pick the desired event occurrence, edit and set exception date.
It's not very convenient and the calendar editor is not adapting well to the mobile phone screen...
As a result, each time I personally have to do it (as a site administrator) instead of the trainer wanting to cancel their event occurrence.

I'm looking for an easier method. GUI for making reservations is nice and easy, and it would be nice to reuse it.

**Comment by yoancutillas** [comment]
Indeed, another possibility is to set an exception date on repeated events to prevent users from booking that occurence.

You can set up permissions to let your trainers manage their calendars and cancel their events by their own ([docs](https://booking-activities.fr/en/docs/user-documentation/advanced-use-of-booking-activities/give-access-rights-to-calendars-and-bookings-to-your-collaborators/)).

I have noted your feature request to allow certain user role to bypass the availability settings (so that a trainer can book the remaining places, but not normal users).

However, making a fake booking with the remaining places in order to make an event unavailable would be a workaround more than a solution. The problem is that the calendar editor is not user-friendly enough on mobile? Or that there are too many clicks before you can cancel an event? Or that you have to do it yourself instead of your trainers?

**Comment by krzysztofmatula** [comment]
I agree what I propose looks like a workaround, not clean feature...

The problem is that the whole Wordpress administration panel is hard to use by non-tech people and I'd rather avoid giving anyone access there.

Maybe something like temporary on/off feature (making the event grayed and thus unavailable for further sign-ups) for event occurrence would be more clean? On a "form" the event could be first selected from a calendar, then maybe a new form element could be added with a button to turn it ON or OFF? I could then prepare such dedicated form on a normal wordpress page with restricted access.
